### PR TITLE
Added 0.15 compat changes

### PR DESCRIPTION
**Pull request by sdobz**
Changes snagged from
https://bitbucket.org/Nicksaurus/foreman/pull-requests/20/015-compat/diff

(See #2)

### CODE REVIEW

**Comment by CodeLenny** [comment]
@sdobz Looks good at first glance, thanks for dealing with `0.15`, I was avoiding dealing with the update.

Long-winded thinking:

It looks like there's also some changes to recipes according to the set `difficulty`, so that might need to be added to officially support 0.15.

I'd like to try running my tests on 0.15, which will require changing `test/assets/download-headless-data.js`.

If this isn't enough to support 0.15, I'll add a disclaimer to the README for now.

---

Actionable steps:

- I'd like to merge your changes into a side branch instead of `master`, let's say named `0.15-compat-lua` so the automated tests can run in Travis.
- In addition, I'd like to see the result of running the tests on `0.15` by changing `download-headless-data`.

If you want, I can deal with changing the MR target and trying the tests on 0.15 either tonight or early tomorrow.

Again, thanks for getting this started!

**Comment by CodeLenny** [comment]
@sdobz Status update: I've added support for testing multiple Factorio versions in the test scripts, and am pushing that through now (#3).  Without your changes, I am getting the `by_pixel` error.

Once #3 hits `master`, I'll see how the tests run `0.15`.

**Comment by CodeLenny** [comment]
@sdobz I've created the `0.15-compat-lua` branch with your changes, and added testing 0.15 to the test configuration.  Looks like everything passes!  https://travis-ci.org/CodeLenny/factorio-recipe-extraction/builds/241562875  (It even improved code coverage!)

I've merged your code into `master`, and closed #1.  I'll be rolling out a `0.1.1` release to NPM.

Thank you for contributing!

**Comment by sdobz** [comment]
Excellent, thanks for your updates! I've been running into a plethora of issues getting server infrastructure onto .15, next up is https://github.com/mroote/factorio-server-manager

**Comment by CodeLenny** [comment]
@sdobz You're welcome!  Good luck getting everything up to 0.15.

Are you currently using `factorio-recipe-extraction`?  I haven't seen anything that people have done with it yet.

**Pull request merged**
